# biography_publisher.py – PDF & DOCX with embedded images (UPDATED with Custom Cover Support)
import streamlit as st
import json
import base64
from datetime import datetime
import re
from openai import OpenAI
import os
import io
from docx import Document
from docx.shared import Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from fpdf import FPDF
import tempfile

st.set_page_config(page_title="Biography Publisher", page_icon="📚", layout="wide")

# Custom CSS
st.markdown("""
<style>
    .main-header { text-align: center; padding: 2rem 0; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                   margin: -1rem -1rem 2rem -1rem; border-radius: 0 0 20px 20px; color: white; }
    .story-card { border-left: 4px solid #667eea; padding: 1rem; margin: 1rem 0; background: #f8f9fa; border-radius: 0 10px 10px 0; }
    .export-box { border: 2px solid #667eea; border-radius: 10px; padding: 2rem; margin: 2rem 0; background: white; }
    .cover-preview { border: 2px solid #ddd; border-radius: 10px; padding: 1rem; margin: 1rem 0; }
</style>
""", unsafe_allow_html=True)

st.markdown('<div class="main-header"><h1>📚 Biography Publisher</h1><p>Transform your stories into a beautifully formatted biography with images</p></div>', unsafe_allow_html=True)

# Initialize session state
if 'stories_data' not in st.session_state:
    st.session_state.stories_data = None
if 'formatted_text' not in st.session_state:
    st.session_state.formatted_text = ""
if 'book_title' not in st.session_state:
    st.session_state.book_title = ""
if 'author_name' not in st.session_state:
    st.session_state.author_name = ""
if 'cover_color' not in st.session_state:
    st.session_state.cover_color = "#2c3e50"
if 'selected_format' not in st.session_state:
    st.session_state.selected_format = "interview"
if 'include_toc' not in st.session_state:
    st.session_state.include_toc = True
if 'include_dates' not in st.session_state:
    st.session_state.include_dates = False
if 'cover_type' not in st.session_state:
    st.session_state.cover_type = "simple"  # "simple" or "custom"
if 'custom_cover_data' not in st.session_state:
    st.session_state.custom_cover_data = None

# ============================================================================
# UPDATED PDF CLASS with Custom Cover Support
# ============================================================================
class PDF(FPDF):
    def __init__(self, custom_cover=None):
        super().__init__()
        self.custom_cover = custom_cover
        
    def header(self):
        if st.session_state.book_title and self.page_no() > 1:
            self.set_font('Arial', 'I', 8)
            self.cell(0, 10, st.session_state.book_title, 0, 0, 'L')
            self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'R')
            self.ln(15)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Generated by Tell My Story • {datetime.now().strftime("%Y")}', 0, 0, 'C')
    
    def add_cover_page(self, book_title, author_name, cover_type="simple", custom_cover=None):
        """Add cover page - either simple gradient or custom designed cover"""
        if cover_type == "custom" and custom_cover:
            # Use the custom cover from the designer
            self.add_custom_cover(custom_cover, book_title, author_name)
        else:
            # Use simple gradient cover
            self.add_simple_cover(book_title, author_name)
    
    def add_simple_cover(self, book_title, author_name):
        """Original simple gradient cover"""
        self.add_page()
        self.set_fill_color(102, 126, 234)
        self.rect(0, 0, 210, 297, 'F')
        self.set_text_color(255, 255, 255)
        self.set_font('Arial', 'B', 30)
        self.cell(0, 40, '', 0, 1)
        self.cell(0, 20, book_title, 0, 1, 'C')
        self.set_font('Arial', '', 16)
        self.cell(0, 10, f'by {author_name}', 0, 1, 'C')
        self.set_font('Arial', '', 12)
        self.cell(0, 10, f'Generated on {datetime.now().strftime("%B %d, %Y")}', 0, 1, 'C')
    
    def add_custom_cover(self, custom_cover, book_title, author_name):
        """Add cover from the cover designer"""
        self.add_page()
        
        # Check if we have a cover image
        if custom_cover.get('cover_image') and os.path.exists(custom_cover['cover_image']):
            # Use the uploaded image as background
            try:
                # Add background image
                self.image(custom_cover['cover_image'], x=0, y=0, w=210, h=297)
                
                # Add semi-transparent overlay for text readability
                self.set_fill_color(0, 0, 0)
                self.set_fill_opacity(0.3)
                self.rect(0, 0, 210, 297, 'F')
                
                # Add title and author from custom cover or use provided
                title = custom_cover.get('title', book_title)
                author = custom_cover.get('author', author_name)
                subtitle = custom_cover.get('subtitle', '')
                
                # Text styling based on custom cover settings
                self.set_text_color(255, 255, 255)
                self.set_font('Arial', 'B', 36)  # Will make this configurable later
                
                # Position text - centered vertically with some spacing
                self.set_y(80)
                self.cell(0, 20, title, 0, 1, 'C')
                
                if subtitle:
                    self.set_font('Arial', '', 20)
                    self.cell(0, 15, subtitle, 0, 1, 'C')
                
                self.set_y(200)
                self.set_font('Arial', '', 24)
                self.cell(0, 15, f'by {author}', 0, 1, 'C')
                
            except Exception as e:
                # Fallback to simple cover if image fails
                st.warning(f"Could not load custom cover image, using simple cover: {e}")
                self.add_simple_cover(book_title, author_name)
        else:
            # No image, use colors from cover designer
            self.add_page()
            
            # Set background color
            bg_color = custom_cover.get('background_color', '#FFFFFF')
            # Convert hex to RGB
            bg_color = bg_color.lstrip('#')
            rgb = tuple(int(bg_color[i:i+2], 16) for i in (0, 2, 4))
            self.set_fill_color(rgb[0], rgb[1], rgb[2])
            self.rect(0, 0, 210, 297, 'F')
            
            # Set title color
            title_color = custom_cover.get('title_color', '#000000')
            title_color = title_color.lstrip('#')
            title_rgb = tuple(int(title_color[i:i+2], 16) for i in (0, 2, 4))
            self.set_text_color(title_rgb[0], title_rgb[1], title_rgb[2])
            
            # Add title with specified font
            title = custom_cover.get('title', book_title)
            subtitle = custom_cover.get('subtitle', '')
            author = custom_cover.get('author', author_name)
            
            self.set_font('Arial', 'B', 36)  # Will map to custom_cover['title_font'] later
            self.cell(0, 40, '', 0, 1)
            self.cell(0, 20, title, 0, 1, 'C')
            
            if subtitle:
                self.set_font('Arial', '', 20)
                self.cell(0, 15, subtitle, 0, 1, 'C')
            
            self.ln(40)
            self.set_font('Arial', '', 24)
            self.cell(0, 15, f'by {author}', 0, 1, 'C')

def set_fill_opacity(self, opacity):
    """Set transparency for fill colors"""
    # Convert opacity (0-1) to alpha value
    alpha = int(opacity * 255)
    self._out(f'{alpha:.0f} w')  # Set line width for transparency
    self._out(f'{alpha} Tr')  # Set rendering mode for transparency

# Add method to FPDF
FPDF.set_fill_opacity = set_fill_opacity

# ============================================================================
# UPDATED PDF GENERATION FUNCTION with Custom Cover Support
# ============================================================================
def generate_pdf(book_title, author_name, stories, format_style, include_toc, include_dates, cover_type="simple", custom_cover=None):
    pdf = PDF(custom_cover)
    
    # Add cover page
    pdf.add_cover_page(book_title, author_name, cover_type, custom_cover)
    
    # Table of Contents
    if include_toc:
        pdf.add_page()
        pdf.set_text_color(0, 0, 0)
        pdf.set_font('Arial', 'B', 20)
        pdf.cell(0, 10, 'Table of Contents', 0, 1, 'C')
        pdf.ln(10)
        pdf.set_font('Arial', '', 12)
        
        if isinstance(stories, list):
            current_session = None
            for i, story in enumerate(stories, 1):
                session_id = story.get('session_id', '1')
                if session_id != current_session:
                    session_title = story.get('session_title', f'Session {session_id}')
                    pdf.set_font('Arial', 'B', 12)
                    pdf.cell(0, 8, session_title, 0, 1)
                    current_session = session_id
                question = story.get('question', f'Story {i}')
                pdf.set_font('Arial', '', 12)
                pdf.cell(10, 6, f'{i}.', 0, 0)
                pdf.cell(0, 6, question[:50] + "..." if len(question) > 50 else question, 0, 1)
        pdf.add_page()

    # Content
    if isinstance(stories, list):
        current_session = None
        story_counter = 1
        for story in stories:
            session_id = story.get('session_id', '1')
            if session_id != current_session:
                session_title = story.get('session_title', f'Session {session_id}')
                pdf.set_font('Arial', 'B', 18)
                pdf.cell(0, 10, session_title, 0, 1, 'L')
                pdf.ln(5)
                current_session = session_id
            
            question = story.get('question', '')
            answer_text = story.get('answer_text', '')
            images = story.get('images', [])
            
            if format_style == 'interview':
                pdf.set_font('Arial', 'B', 12)
                pdf.multi_cell(0, 6, f'Q: {question}')
                pdf.ln(2)
                pdf.set_font('Arial', '', 11)
                pdf.multi_cell(0, 6, answer_text)
            elif format_style == 'biography':
                pdf.set_font('Arial', '', 11)
                pdf.multi_cell(0, 6, answer_text)
            else:  # memoir
                pdf.set_font('Arial', 'B', 14)
                pdf.cell(0, 8, f'Chapter {story_counter}: {question}', 0, 1)
                pdf.ln(4)
                pdf.set_font('Arial', '', 11)
                pdf.multi_cell(0, 6, answer_text)
            
            # Embed images
            for img_data in images:
                b64 = img_data.get('base64')
                caption = img_data.get('caption', '')
                if b64:
                    try:
                        img_bytes = base64.b64decode(b64)
                        with tempfile.NamedTemporaryFile(delete=False, suffix='.jpg') as tmp:
                            tmp.write(img_bytes)
                            tmp_path = tmp.name
                        pdf.image(tmp_path, w=100)
                        os.unlink(tmp_path)
                        if caption:
                            pdf.set_font('Arial', 'I', 10)
                            pdf.cell(0, 6, f'📝 {caption}', 0, 1, 'C')
                        pdf.ln(5)
                    except Exception as e:
                        st.warning(f"Could not embed image: {e}")
            pdf.ln(5)
            story_counter += 1

    return pdf.output(dest='S').encode('latin1', errors='ignore')

# ============================================================================
# UPDATED DOCX GENERATION FUNCTION (for future custom cover support)
# ============================================================================
def generate_docx(book_title, author_name, stories, format_style, include_toc, include_dates, cover_type="simple", custom_cover=None):
    doc = Document()
    
    # Title page - can be customized later
    title = doc.add_heading(book_title, 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    author = doc.add_paragraph(f'by {author_name}')
    author.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_para = doc.add_paragraph(f'Generated on {datetime.now().strftime("%B %d, %Y")}')
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_page_break()
    
    # TOC
    if include_toc:
        doc.add_heading('Table of Contents', 1).alignment = WD_ALIGN_PARAGRAPH.CENTER
        if isinstance(stories, list):
            current_session = None
            for i, story in enumerate(stories, 1):
                session_id = story.get('session_id', '1')
                if session_id != current_session:
                    session_title = story.get('session_title', f'Session {session_id}')
                    doc.add_heading(session_title, 2)
                    current_session = session_id
                question = story.get('question', f'Story {i}')
                p = doc.add_paragraph(f'{i}. {question}')
                p.style = 'List Bullet'
        doc.add_page_break()
    
    # Content
    if isinstance(stories, list):
        current_session = None
        story_counter = 1
        for story in stories:
            session_id = story.get('session_id', '1')
            if session_id != current_session:
                session_title = story.get('session_title', f'Session {session_id}')
                doc.add_heading(session_title, 1)
                current_session = session_id
            question = story.get('question', '')
            answer_text = story.get('answer_text', '')
            images = story.get('images', [])
            
            if format_style == 'interview':
                doc.add_heading(f'Q: {question}', 3)
                doc.add_paragraph(answer_text)
            elif format_style == 'biography':
                doc.add_paragraph(answer_text)
            else:
                doc.add_heading(f'Chapter {story_counter}: {question}', 2)
                doc.add_paragraph(answer_text)
            
            # Embed images
            for img_data in images:
                b64 = img_data.get('base64')
                caption = img_data.get('caption', '')
                if b64:
                    try:
                        img_bytes = base64.b64decode(b64)
                        img_stream = io.BytesIO(img_bytes)
                        doc.add_picture(img_stream, width=Inches(4))
                        if caption:
                            cap = doc.add_paragraph(caption)
                            cap.style = 'Caption'
                    except:
                        pass
            doc.add_paragraph()
            story_counter += 1
    
    docx_bytes = io.BytesIO()
    doc.save(docx_bytes)
    docx_bytes.seek(0)
    return docx_bytes

# ============================================================================
# SIDEBAR SETTINGS (Updated with Cover Type Option)
# ============================================================================
with st.sidebar:
    st.header("⚙️ Publication Settings")
    st.subheader("Book Details")
    st.session_state.book_title = st.text_input("Book Title", value=st.session_state.book_title)
    st.session_state.author_name = st.text_input("Author Name", value=st.session_state.author_name)
    
    # Cover Type Selection
    st.subheader("🎨 Cover Design")
    cover_type = st.radio(
        "Cover Style",
        ["simple", "custom"],
        format_func=lambda x: "🌈 Simple Gradient Cover" if x == "simple" else "🎨 Use My Custom Cover Design",
        index=0 if st.session_state.cover_type == "simple" else 1,
        key="cover_type_radio"
    )
    st.session_state.cover_type = cover_type
    
    if cover_type == "custom":
        st.info("Your custom cover from the main app will be used automatically")
        if st.session_state.custom_cover_data:
            with st.expander("Preview Custom Cover", expanded=False):
                if st.session_state.custom_cover_data.get('cover_image') and os.path.exists(st.session_state.custom_cover_data['cover_image']):
                    st.image(st.session_state.custom_cover_data['cover_image'], width=200)
                st.markdown(f"**Title:** {st.session_state.custom_cover_data.get('title', 'N/A')}")
                st.markdown(f"**Author:** {st.session_state.custom_cover_data.get('author', 'N/A')}")
    
    st.subheader("Format Options")
    st.session_state.selected_format = st.radio(
        "Format Style",
        ["interview", "biography", "memoir"],
        format_func=lambda x: {"interview": "📝 Interview Q&A", "biography": "📖 Continuous Biography", "memoir": "📚 Chapter-based Memoir"}[x]
    )
    col1, col2 = st.columns(2)
    with col1:
        st.session_state.include_toc = st.checkbox("Table of Contents", value=True)
    with col2:
        st.session_state.include_dates = st.checkbox("Include Dates", value=False)
    
    st.divider()
    st.subheader("📂 Upload Stories")
    uploaded_file = st.file_uploader("Upload JSON from Tell My Story", type=['json'])
    if uploaded_file:
        try:
            st.session_state.stories_data = json.load(uploaded_file)
            st.success("✅ Uploaded successfully!")
            # Auto-fill title/author from profile
            user_profile = st.session_state.stories_data.get('user_profile', {})
            if user_profile:
                first = user_profile.get('first_name', '')
                last = user_profile.get('last_name', '')
                if first and last:
                    st.session_state.author_name = f"{first} {last}"
                    st.session_state.book_title = f"The Story of {first} {last}"
        except Exception as e:
            st.error(f"Error loading file: {e}")

# ============================================================================
# MAIN INTERFACE
# ============================================================================
if st.session_state.stories_data:
    stories_data = st.session_state.stories_data
    stories = stories_data.get('stories', [])
    user_profile = stories_data.get('user_profile', {})

    # Display summary
    st.subheader("📊 Data Summary")
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Total Stories", stories_data.get('summary', {}).get('total_stories', len(stories)))
    with col2:
        st.metric("Sessions", stories_data.get('summary', {}).get('total_sessions', 1))
    with col3:
        st.metric("Export Date", stories_data.get('export_date', 'Unknown')[:10])

    # Preview
    with st.expander("📖 Preview Stories", expanded=False):
        for i, story in enumerate(stories[:3]):
            st.markdown(f"**Q: {story.get('question', '')}**")
            st.markdown(f"*{story.get('answer_text', '')[:200]}...*")
            if story.get('images'):
                st.caption(f"📸 {len(story['images'])} image(s) attached")
            st.divider()
        if len(stories) > 3:
            st.info(f"... and {len(stories) - 3} more stories")

    # Preview custom cover if available
    if st.session_state.cover_type == "custom" and st.session_state.custom_cover_data:
        with st.expander("🎨 Custom Cover Preview", expanded=True):
            col1, col2 = st.columns([1, 2])
            with col1:
                if st.session_state.custom_cover_data.get('cover_image') and os.path.exists(st.session_state.custom_cover_data['cover_image']):
                    st.image(st.session_state.custom_cover_data['cover_image'], width=200)
                else:
                    st.markdown(f"**Background:** {st.session_state.custom_cover_data.get('background_color', '#FFFFFF')}")
            with col2:
                st.markdown(f"**Title:** {st.session_state.custom_cover_data.get('title', 'N/A')}")
                st.markdown(f"**Subtitle:** {st.session_state.custom_cover_data.get('subtitle', 'N/A')}")
                st.markdown(f"**Author:** {st.session_state.custom_cover_data.get('author', 'N/A')}")
                st.markdown(f"**Style:** {st.session_state.custom_cover_data.get('cover_type', 'Simple')}")
                st.markdown(f"**Font:** {st.session_state.custom_cover_data.get('title_font', 'Georgia')}")

    # Formatting controls
    st.subheader("🖨️ Generate Biography")
    col1, col2, col3 = st.columns(3)
    
    with col1:
        if st.button("📊 Generate DOCX", type="primary", use_container_width=True):
            with st.spinner("Creating Word document with images..."):
                docx_bytes = generate_docx(
                    st.session_state.book_title,
                    st.session_state.author_name,
                    stories,
                    st.session_state.selected_format,
                    st.session_state.include_toc,
                    st.session_state.include_dates,
                    st.session_state.cover_type,
                    st.session_state.custom_cover_data
                )
                filename = f"{st.session_state.book_title.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d')}.docx"
                st.download_button(
                    "📥 Download DOCX", 
                    data=docx_bytes, 
                    file_name=filename, 
                    mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document", 
                    use_container_width=True,
                    key="docx_download_btn"
                )
    
    with col2:
        if st.button("📕 Generate PDF", type="primary", use_container_width=True):
            with st.spinner("Creating PDF with images..."):
                pdf_bytes = generate_pdf(
                    st.session_state.book_title,
                    st.session_state.author_name,
                    stories,
                    st.session_state.selected_format,
                    st.session_state.include_toc,
                    st.session_state.include_dates,
                    st.session_state.cover_type,
                    st.session_state.custom_cover_data
                )
                filename = f"{st.session_state.book_title.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d')}.pdf"
                st.download_button(
                    "📥 Download PDF", 
                    data=pdf_bytes, 
                    file_name=filename, 
                    mime="application/pdf", 
                    use_container_width=True,
                    key="pdf_download_btn"
                )
    
    with col3:
        if st.button("📄 Preview Text", use_container_width=True):
            preview = f"{st.session_state.book_title}\nby {st.session_state.author_name}\n\n"
            preview += f"Cover Style: {'Custom Design' if st.session_state.cover_type == 'custom' else 'Simple Gradient'}\n\n"
            for i, story in enumerate(stories[:5]):
                preview += f"Story {i+1}: {story.get('question', '')}\n"
                preview += f"{story.get('answer_text', '')[:200]}...\n\n"
            st.session_state.formatted_text = preview
    
    # Show preview if available
    if st.session_state.formatted_text:
        with st.expander("📄 Text Preview", expanded=True):
            st.text_area("Preview", st.session_state.formatted_text, height=300)

else:
    st.info("📚 Upload your stories JSON file using the sidebar to begin.")
    st.markdown("""
    ### How to use:
    1. Export your data from the **Tell My Story** app
    2. Upload the JSON file using the sidebar
    3. Choose between **Simple Gradient** or **Custom Cover Design**
    4. Customize your book settings
    5. Generate PDF or DOCX with embedded images
    
    ### Custom Cover Support:
    - Use the Cover Designer in the main app to create your cover
    - Your custom cover (title, subtitle, author, colors, images) will be used automatically
    - Preview your cover before generating
    """)

st.markdown("---")
st.caption(f"Biography Publisher • {datetime.now().year}")
st.caption(f"Biography Publisher • {datetime.now().year}")


