def render_disclaimer(self):
    """Render the complete disclaimer section"""
    
    st.markdown("""
    <div style="
        background-color: #f8f9fa;
        border-left: 4px solid #6c757d;
        padding: 20px;
        margin: 20px 0;
        border-radius: 8px;
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        line-height: 1.6;
    ">
        <h3 style="color: #2c3e50; margin-top: 0;">📋 IMPORTANT DISCLAIMER</h3>
    """, unsafe_allow_html=True)
    
    # Plain text date - no HTML
    st.markdown("**Last Updated: February 21, 2026**")
    
    # Create expandable sections for each part of the disclaimer
    with st.expander("1. ACCURACY OF CONTENT", expanded=True):
        st.markdown("""
        The biographical content, stories, and personal narratives created using Tell My Story are based entirely on information, memories, and materials provided by you, the user. While we strive to assist you in creating well-written narratives, we cannot independently verify the factual accuracy of:
        
        - Personal memories, dates, and historical events
        - Family histories and genealogical information
        - Stories about other individuals
        - Photographs and their metadata
        - Documents and other uploaded materials
        
        **You are solely responsible for ensuring the accuracy of all information you input into the application.**
        """)
    
    with st.expander("2. AI-GENERATED CONTENT", expanded=True):
        st.markdown("""
        Tell My Story uses artificial intelligence (AI) tools including OpenAI's GPT models to provide:
        - Spelling and grammar correction
        - Writing assistance and rewrites
        - Beta reader feedback and analysis
        - Writing suggestions and improvements
        
        **IMPORTANT:** AI-generated suggestions are provided as assists only. You should review all AI-generated content for accuracy, appropriateness, and alignment with your voice before using it in your final work. AI may occasionally generate incorrect information or content that doesn't accurately reflect your intended meaning.
        """)
    
    with st.expander("3. PRIVACY & DATA HANDLING", expanded=True):
        st.markdown("""
        - Your stories and personal information are stored locally or on your own secure servers
        - We do not train AI models on your personal data
        - Content sent to OpenAI for AI features (spell check, rewrites, beta reading) is processed according to OpenAI's API data usage policies
        - You retain full ownership and copyright of all content you create
        - We recommend not including sensitive personal information like social security numbers, financial account details, or passwords
        """)
    
    with st.expander("4. LEGAL CONSIDERATIONS FOR BIOGRAPHIES", expanded=True):
        st.markdown("""
        When writing about real people (including family members, friends, or colleagues), you are responsible for:
        
        - **Defamation:** Ensuring your stories do not contain false statements that could harm someone's reputation
        - **Privacy Rights:** Respecting the privacy of living individuals
        - **Copyright:** Obtaining necessary permissions for quoted materials, letters, or third-party content
        - **Right of Publicity:** Understanding laws regarding using names or likenesses of living persons
        
        **We strongly recommend consulting with a legal professional if your biography includes potentially sensitive content about living individuals.**
        """)
    
    with st.expander("5. NO LEGAL OR PROFESSIONAL ADVICE", expanded=True):
        st.markdown("""
        Tell My Story is a writing tool and does not provide:
        - Legal advice regarding publishing, defamation, or privacy laws
        - Professional counseling or therapeutic services
        - Medical or mental health advice
        - Financial or investment guidance
        
        If you need professional advice in these areas, please consult qualified professionals.
        """)
    
    with st.expander("6. BETA READER FEEDBACK", expanded=True):
        st.markdown("""
        The Beta Reader feature provides AI-generated feedback on your writing. This feedback is:
        - Generated by artificial intelligence, not human readers
        - Intended for informational and improvement purposes only
        - Not a substitute for professional editing services
        - Based on patterns in your writing, not absolute literary judgment
        """)
    
    with st.expander("7. EXPORTED FILES", expanded=True):
        st.markdown("""
        When you export your book in DOCX, HTML, EPUB, or RTF formats:
        - Formatting may vary slightly depending on the software used to open the files
        - We recommend previewing exported files before final distribution
        - Embedded images may appear differently across various devices and readers
        """)
    
    with st.expander("8. THIRD-PARTY SERVICES", expanded=True):
        st.markdown("""
        Tell My Story may integrate with third-party services including:
        - OpenAI (for AI writing features)
        - Email services (for account notifications)
        
        Your use of these features is subject to the terms of service and privacy policies of these third-party providers.
        """)
    
    with st.expander("9. NO WARRANTIES", expanded=True):
        st.markdown("""
        Tell My Story is provided "as is" without any warranties, express or implied. We do not guarantee that:
        - The application will be error-free or uninterrupted
        - AI features will produce perfect results
        - Exported files will be compatible with all software versions
        - Your data will never be lost (please maintain your own backups)
        """)
    
    with st.expander("10. LIMITATION OF LIABILITY", expanded=True):
        st.markdown("""
        To the maximum extent permitted by law, Tell My Story and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from:
        - Your use or inability to use the application
        - Any content created using the application
        - Unauthorized access to or alteration of your content
        - Statements or conduct of any third party
        """)
    
    with st.expander("11. YOUR ACKNOWLEDGMENT", expanded=True):
        st.markdown("""
        **BY USING TELL MY STORY, YOU ACKNOWLEDGE THAT YOU HAVE READ THIS DISCLAIMER AND AGREE TO BE BOUND BY ITS TERMS.**
        
        ---
        
        *For questions about this disclaimer, please contact support.*
        """)
    
    # Add download button for disclaimer
    disclaimer_text = """# DISCLAIMER - Tell My Story

**Last Updated: February 21, 2026**

## 1. ACCURACY OF CONTENT
The biographical content, stories, and personal narratives created using Tell My Story are based entirely on information, memories, and materials provided by you, the user. While we strive to assist you in creating well-written narratives, we cannot independently verify the factual accuracy of:

- Personal memories, dates, and historical events
- Family histories and genealogical information
- Stories about other individuals
- Photographs and their metadata
- Documents and other uploaded materials

**You are solely responsible for ensuring the accuracy of all information you input into the application.**

## 2. AI-GENERATED CONTENT
Tell My Story uses artificial intelligence (AI) tools including OpenAI's GPT models to provide:
- Spelling and grammar correction
- Writing assistance and rewrites
- Beta reader feedback and analysis
- Writing suggestions and improvements

**IMPORTANT:** AI-generated suggestions are provided as assists only. You should review all AI-generated content for accuracy, appropriateness, and alignment with your voice before using it in your final work. AI may occasionally generate incorrect information or content that doesn't accurately reflect your intended meaning.

## 3. PRIVACY & DATA HANDLING
- Your stories and personal information are stored locally or on your own secure servers
- We do not train AI models on your personal data
- Content sent to OpenAI for AI features (spell check, rewrites, beta reading) is processed according to OpenAI's API data usage policies
- You retain full ownership and copyright of all content you create
- We recommend not including sensitive personal information like social security numbers, financial account details, or passwords

## 4. LEGAL CONSIDERATIONS FOR BIOGRAPHIES
When writing about real people (including family members, friends, or colleagues), you are responsible for:

- **Defamation:** Ensuring your stories do not contain false statements that could harm someone's reputation
- **Privacy Rights:** Respecting the privacy of living individuals
- **Copyright:** Obtaining necessary permissions for quoted materials, letters, or third-party content
- **Right of Publicity:** Understanding laws regarding using names or likenesses of living persons

**We strongly recommend consulting with a legal professional if your biography includes potentially sensitive content about living individuals.**

## 5. NO LEGAL OR PROFESSIONAL ADVICE
Tell My Story is a writing tool and does not provide:
- Legal advice regarding publishing, defamation, or privacy laws
- Professional counseling or therapeutic services
- Medical or mental health advice
- Financial or investment guidance

If you need professional advice in these areas, please consult qualified professionals.

## 6. BETA READER FEEDBACK
The Beta Reader feature provides AI-generated feedback on your writing. This feedback is:
- Generated by artificial intelligence, not human readers
- Intended for informational and improvement purposes only
- Not a substitute for professional editing services
- Based on patterns in your writing, not absolute literary judgment

## 7. EXPORTED FILES
When you export your book in DOCX, HTML, EPUB, or RTF formats:
- Formatting may vary slightly depending on the software used to open the files
- We recommend previewing exported files before final distribution
- Embedded images may appear differently across various devices and readers

## 8. THIRD-PARTY SERVICES
Tell My Story may integrate with third-party services including:
- OpenAI (for AI writing features)
- Email services (for account notifications)

Your use of these features is subject to the terms of service and privacy policies of these third-party providers.

## 9. NO WARRANTIES
Tell My Story is provided "as is" without any warranties, express or implied. We do not guarantee that:
- The application will be error-free or uninterrupted
- AI features will produce perfect results
- Exported files will be compatible with all software versions
- Your data will never be lost (please maintain your own backups)

## 10. LIMITATION OF LIABILITY
To the maximum extent permitted by law, Tell My Story and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from:
- Your use or inability to use the application
- Any content created using the application
- Unauthorized access to or alteration of your content
- Statements or conduct of any third party

## 11. YOUR ACKNOWLEDGMENT
**BY USING TELL MY STORY, YOU ACKNOWLEDGE THAT YOU HAVE READ THIS DISCLAIMER AND AGREE TO BE BOUND BY ITS TERMS.**

---

*For questions about this disclaimer, please contact support.*
"""
    
    st.download_button(
        label="📥 Download Disclaimer as Text File",
        data=disclaimer_text,
        file_name="Tell_My_Story_Disclaimer.txt",
        mime="text/plain",
        use_container_width=True
    )
